Docker build -t wipro .

Docker run -d --name wipro -p 9000:3000 arjun



version: '3.8'

services:
  wipro:
    image: arjun
    build: .
    ports:
      - '9000:3000'
    environment:
      - MONGODB_URI || 'mongodb://localhost:27017/transactionhistory'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'




